version: '3'

services:
  janparras:
    container_name: janparras
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8007:3000"
    environment:
      - NODE_ENV=production
